server:
  port: 9001
spring:
  application:
    name: springcloud-eureka-client # 指定微服务的名称后续在调用的时候只需要使用该名称就可以进行服务的访问，在eureka客户端UI中也宣誓这个名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
logging:
  pattern:
    #console: %d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n
    #file: %d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n
  path: D:/Workpaces/IdeaWorkspace/springcloud/
  file: logging.log
  #level: trace